[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "bash runner.sh"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
